name: Release Artifacts
on:
  push:
    tags: ['v*.*.*']
  workflow_dispatch: {}
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
          chmod +x opa
          sudo mv opa /usr/local/bin/opa
      - name: Run assessment (E2E minimal)
        env:
          SKIP_EBPF: 1
          SKIP_AWS: 1
        run: |
          bash scripts/run_assessment.sh
      - name: Build release bundles
        run: |
          chmod +x scripts/build_release_bundle.sh || true
          bash scripts/build_release_bundle.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
