name: Deploy Site (Cloudflare Pages)

on:
  push:
    branches: [ main ]
    paths:
      - 'carnot-site/**'
      - '.github/workflows/site.yml'
      - 'docs/samples/**'
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: carnotengine-site
          directory: carnot-site
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: '3'

      - name: Post links
        if: success()
        run: |
          echo "Deployed site (see Cloudflare Pages dashboard for URL)."
