name: Stress & Overhead (Linux)

on:
  workflow_dispatch:
    inputs:
      duration:
        description: Seconds to run stress test
        required: false
        default: '30'
      target:
        description: HTTP target URL
        required: false
        default: 'https://example.org'
  push:
    paths:
      - 'scripts/stress_test.sh'
      - 'carnot-agent/ebpf-core/**'
      - '.github/workflows/stress.yml'

jobs:
  stress:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install base deps
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y clang llvm make golang-go jq libbpf-dev linux-headers-$(uname -r) git build-essential libelf-dev zlib1g-dev pkg-config
          go install github.com/rakyll/hey@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Setup bpftool (composite action)
        uses: ./.github/actions/setup-bpftool
        with:
          version: v7.3.0
      - name: Go module tidy (generate go.sum)
        run: |
          cd carnot-agent/ebpf-core/go-loader
          go mod tidy
          ls -l go.mod go.sum
      - name: Build eBPF & loader
        run: |
          cd carnot-agent/ebpf-core
          make all
          cd go-loader
          mkdir -p bin
          go build -o bin/carnot-ebpf-loader .
      - name: Run stress test
        run: |
          DURATION=${{ github.event.inputs.duration || '30' }}
          TARGET=${{ github.event.inputs.target || 'https://example.org' }}
          bash scripts/stress_test.sh "$TARGET" "$DURATION" metrics.json
      - name: Show metrics.json
        run: cat metrics.json
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: stress-metrics
          path: |
            metrics.json
            docs/OVERHEAD_RESULTS.md
            runtime.jsonl
            loader_metrics.json
            loader_stress.log
      - name: Append summary
        run: |
          echo '### Stress Test Metrics' >> $GITHUB_STEP_SUMMARY
          echo '\n```json' >> $GITHUB_STEP_SUMMARY
          cat metrics.json >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
