name: Worklog Check
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure WORKLOG updated or bypass label present
        run: |
          set -e
          PR=${{ github.event.pull_request.number }}
          BYPASS=$(gh pr view $PR --json labels -q '.labels[].name' | grep -c '^worklog-bypass$' || true)
          if [ "$BYPASS" -gt 0 ]; then echo "Bypass label present"; exit 0; fi
          git fetch origin ${{ github.base_ref }} --depth=1
          if git diff --name-only HEAD origin/${{ github.base_ref }} | grep -q '^WORKLOG.md$'; then
            echo "WORKLOG updated"; exit 0;
          else
            echo "::error::WORKLOG.md not updated. Add entry or apply 'worklog-bypass' label."
            exit 1
          fi
        env: { GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} }
